import _sodium from 'libsodium-wrappers';

// Base64 encoded file contents to avoid JS parser string termination issues
const WORKFLOW_YAML_B64 = "bmFtZTogUmVwb093bCBQUiBBbmFseXplcg0KDQpvbjoNCiAgcHVsbF9yZXF1ZXN0X3RhcmdldDoNCiAgICB0eXBlczogW29wZW5lZCwgcmVhZHlfZm9yX3Jldmlld10NCiAgaXNzdWVfY29tbWVudDoNCiAgICB0eXBlczogW2NyZWF0ZWRdDQoNCnBlcm1pc3Npb25zOg0KICBwdWxsLXJlcXVlc3RzOiB3cml0ZQ0KICBpc3N1ZXM6IHdyaXRlDQogIGNvbnRlbnRzOiByZWFkDQoNCmpvYnM6DQogIGFuYWx5emUtcHI6DQogICAgIyBPbmx5IHJ1biBpZiBpdCdzIGEgUFIgY3JlYXRpb24gT1IgaWYgdGhlIGNvbW1lbnQgY29udGFpbnMgZXhhY3RseSAiL2FuYWx5emUiIChvciAiL2FuYWx5c2UiKQ0KICAgIGlmOiA+DQogICAgICBnaXRodWIuZXZlbnRfbmFtZSA9PSAncHVsbF9yZXF1ZXN0X3RhcmdldCcgfHwNCiAgICAgIChnaXRodWIuZXZlbnQuaXNzdWUucHVsbF9yZXF1ZXN0ICYmIChjb250YWlucyhnaXRodWIuZXZlbnQuY29tbWVudC5ib2R5LCAnL2FuYWx5emUnKSB8fCBjb250YWlucyhnaXRodWIuZXZlbnQuY29tbWVudC5ib2R5LCAnL2FuYWx5c2UnKSkpDQoNCiAgICBydW5zLW9uOiB1YnVudHUtbGF0ZXN0DQoNCiAgICBzdGVwczoNCiAgICAgIC0gbmFtZTogQ2hlY2tvdXQgUmVwb3NpdG9yeQ0KICAgICAgICB1c2VzOiBhY3Rpb25zL2NoZWNrb3V0QHY0DQoNCiAgICAgIC0gbmFtZTogU2V0dXAgTm9kZS5qcw0KICAgICAgICB1c2VzOiBhY3Rpb25zL3NldHVwLW5vZGVAdjQNCiAgICAgICAgd2l0aDoNCiAgICAgICAgICBub2RlLXZlcnNpb246ICcyMCcNCg0KDQogICAgICAtIG5hbWU6IFJ1biBSZXBvT3dsIFBSIEFuYWx5c2lzDQogICAgICAgIGVudjoNCiAgICAgICAgICBHUk9RX0FQSV9LRVk6ICR7eyBzZWNyZXRzLkdST1FfQVBJX0tFWSB9fQ0KICAgICAgICAgIEdJVEhVQl9UT0tFTjogJHt7IHNlY3JldHMuR0lUSFVCX1RPS0VOIH19DQogICAgICAgICAgUFJfTlVNQkVSOiAke3sgZ2l0aHViLmV2ZW50LnB1bGxfcmVxdWVzdC5udW1iZXIgfHwgZ2l0aHViLmV2ZW50Lmlzc3VlLm51bWJlciB9fQ0KICAgICAgICAgIFJFUE9TSVRPUlk6ICR7eyBnaXRodWIucmVwb3NpdG9yeSB9fQ0KICAgICAgICBydW46IG5vZGUgLmdpdGh1Yi9zY3JpcHRzL2FuYWx5emUtcHIuanMNCg==";
const SCRIPT_JS_B64 = "DQoNCmNvbnN0IEdST1FfQVBJX0tFWSA9IHByb2Nlc3MuZW52LkdST1FfQVBJX0tFWTsNCmNvbnN0IEdJVEhVQl9UT0tFTiA9IHByb2Nlc3MuZW52LkdJVEhVQl9UT0tFTjsNCmNvbnN0IFBSX05VTUJFUiA9IHByb2Nlc3MuZW52LlBSX05VTUJFUjsNCmNvbnN0IFJFUE9TSVRPUlkgPSBwcm9jZXNzLmVudi5SRVBPU0lUT1JZOyAvLyBmb3JtYXQ6IG93bmVyL3JlcG8NCg0KY29uc3QgR1JPUV9VUkwgPSAnaHR0cHM6Ly9hcGkuZ3JvcS5jb20vb3BlbmFpL3YxL2NoYXQvY29tcGxldGlvbnMnOw0KY29uc3QgTU9ERUxfTkFNRSA9ICdsbGFtYS0zLjMtNzBiLXZlcnNhdGlsZSc7DQoNCmFzeW5jIGZ1bmN0aW9uIGFza0dyb3EocHJvbXB0KSB7DQogIGNvbnN0IHJlc3BvbnNlID0gYXdhaXQgZmV0Y2goR1JPUV9VUkwsIHsNCiAgICBtZXRob2Q6ICdQT1NUJywNCiAgICBoZWFkZXJzOiB7DQogICAgICAnQXV0aG9yaXphdGlvbic6IGBCZWFyZXIgJHtHUk9RX0FQSV9LRVl9YCwNCiAgICAgICdDb250ZW50LVR5cGUnOiAnYXBwbGljYXRpb24vanNvbicNCiAgICB9LA0KICAgIGJvZHk6IEpTT04uc3RyaW5naWZ5KHsNCiAgICAgIG1vZGVsOiBNT0RFTF9OQU1FLA0KICAgICAgbWVzc2FnZXM6IFt7IHJvbGU6ICJ1c2VyIiwgY29udGVudDogcHJvbXB0IH1dDQogICAgfSkNCiAgfSk7DQogIGlmICghcmVzcG9uc2Uub2spIHsNCiAgICBjb25zdCBlcnJvclRleHQgPSBhd2FpdCByZXNwb25zZS50ZXh0KCk7DQogICAgdGhyb3cgbmV3IEVycm9yKGBHcm9xIEFQSSBlcnJvcjogJHtlcnJvclRleHR9YCk7DQogIH0NCiAgY29uc3QgZGF0YSA9IGF3YWl0IHJlc3BvbnNlLmpzb24oKTsNCiAgcmV0dXJuIGRhdGEuY2hvaWNlc1swXS5tZXNzYWdlLmNvbnRlbnQ7DQp9DQoNCmFzeW5jIGZ1bmN0aW9uIHJ1bigpIHsNCiAgaWYgKCFHUk9RX0FQSV9LRVkgfHwgIUdJVEhVQl9UT0tFTikgew0KICAgIGNvbnNvbGUud2Fybigi4pqg77iPICBTa2lwcGluZyBSZXBvT3dsIFBSIEFuYWx5c2lzOiBNaXNzaW5nIEdST1FfQVBJX0tFWSBvciBHSVRIVUJfVE9LRU4gc2VjcmV0LiBQbGVhc2UgY29uZmlndXJlIHRoZXNlIGluIHlvdXIgcmVwb3NpdG9yeSBzZWNyZXRzLiIpOw0KICAgIHByb2Nlc3MuZXhpdCgwKTsNCiAgfQ0KDQogIGNvbnNvbGUubG9nKGBTdGFydGluZyBSZXBvT3dsIE1hcC1SZWR1Y2UgQW5hbHlzaXMgZm9yIFBSICMke1BSX05VTUJFUn0gaW4gJHtSRVBPU0lUT1JZfS4uLmApOw0KDQogIC8vIDEuIEZldGNoIFBSIERldGFpbHMNCiAgY29uc3QgcHJSZXNwb25zZSA9IGF3YWl0IGZldGNoKGBodHRwczovL2FwaS5naXRodWIuY29tL3JlcG9zLyR7UkVQT1NJVE9SWX0vcHVsbHMvJHtQUl9OVU1CRVJ9YCwgew0KICAgIGhlYWRlcnM6IHsgJ0F1dGhvcml6YXRpb24nOiBgQmVhcmVyICR7R0lUSFVCX1RPS0VOfWAgfQ0KICB9KTsNCiAgY29uc3QgcHJEYXRhID0gYXdhaXQgcHJSZXNwb25zZS5qc29uKCk7DQoNCiAgLy8gMi4gRmV0Y2ggUFIgRGlmZnMNCiAgY29uc3QgZGlmZlJlc3BvbnNlID0gYXdhaXQgZmV0Y2goYGh0dHBzOi8vYXBpLmdpdGh1Yi5jb20vcmVwb3MvJHtSRVBPU0lUT1JZfS9wdWxscy8ke1BSX05VTUJFUn0vZmlsZXNgLCB7DQogICAgaGVhZGVyczogeyAnQXV0aG9yaXphdGlvbic6IGBCZWFyZXIgJHtHSVRIVUJfVE9LRU59YCB9DQogIH0pOw0KICBjb25zdCBmaWxlc0RhdGEgPSBhd2FpdCBkaWZmUmVzcG9uc2UuanNvbigpOw0KDQogIC8vIDMuIENoZWNrIGZvciBMaW5rZWQgSXNzdWVzDQogIGxldCBsaW5rZWRJc3N1ZUNvbnRleHQgPSAiTm8gbGlua2VkIGlzc3VlIGRldGVjdGVkLiI7DQogIGNvbnN0IGlzc3VlTWF0Y2ggPSBwckRhdGEuYm9keSA/IHByRGF0YS5ib2R5Lm1hdGNoKC8oPzpmaXh8Zml4ZXN8cmVzb2x2ZXN8Y2xvc2VzKVxzKyMoXGQrKS9pKSA6IG51bGw7DQogIA0KICBpZiAoaXNzdWVNYXRjaCkgew0KICAgIGNvbnN0IGlzc3VlTnVtID0gaXNzdWVNYXRjaFsxXTsNCiAgICBjb25zb2xlLmxvZyhgRGV0ZWN0ZWQgbGlua2VkIGlzc3VlICMke2lzc3VlTnVtfS4gRmV0Y2hpbmcgY29udGV4dC4uLmApOw0KICAgIGNvbnN0IGlzc3VlUmVzID0gYXdhaXQgZmV0Y2goYGh0dHBzOi8vYXBpLmdpdGh1Yi5jb20vcmVwb3MvJHtSRVBPU0lUT1JZfS9pc3N1ZXMvJHtpc3N1ZU51bX1gLCB7DQogICAgICBoZWFkZXJzOiB7ICdBdXRob3JpemF0aW9uJzogYEJlYXJlciAke0dJVEhVQl9UT0tFTn1gIH0NCiAgICB9KTsNCiAgICBpZiAoaXNzdWVSZXMub2spIHsNCiAgICAgIGNvbnN0IGlzc3VlRGV0YWlscyA9IGF3YWl0IGlzc3VlUmVzLmpzb24oKTsNCiAgICAgIGxpbmtlZElzc3VlQ29udGV4dCA9IGBMaW5rZWQgSXNzdWUgR29hbDogJHtpc3N1ZURldGFpbHMudGl0bGV9XG4ke2lzc3VlRGV0YWlscy5ib2R5fWA7DQogICAgfQ0KICB9DQoNCiAgLy8gNC4gTUFQIFBIQVNFOiBTdW1tYXJpemUgaW5kaXZpZHVhbCBmaWxlcw0KICBjb25zdCBmaWx0ZXJlZEZpbGVzID0gZmlsZXNEYXRhLmZpbHRlcihmID0+IA0KICAgICFmLmZpbGVuYW1lLmluY2x1ZGVzKCdwYWNrYWdlLWxvY2suanNvbicpICYmIA0KICAgICFmLmZpbGVuYW1lLmVuZHNXaXRoKCcuc3ZnJykgJiYNCiAgICBmLnBhdGNoDQogICk7DQoNCiAgY29uc29sZS5sb2coYE1hcHBpbmcgJHtmaWx0ZXJlZEZpbGVzLmxlbmd0aH0gZmlsZXMuLi5gKTsNCiAgY29uc3QgZmlsZVN1bW1hcmllcyA9IFtdOw0KICANCiAgZm9yIChjb25zdCBmaWxlIG9mIGZpbHRlcmVkRmlsZXMpIHsNCiAgICB0cnkgew0KICAgICAgY29uc29sZS5sb2coYFN1bW1hcml6aW5nICR7ZmlsZS5maWxlbmFtZX0uLi5gKTsNCiAgICAgIGNvbnN0IG1hcFByb21wdCA9IGANCiAgICAgICAgQnJpZWZseSBzdW1tYXJpemUgd2hhdCB0aGlzIHNwZWNpZmljIGZpbGUgZGlmZiBkb2VzIGluIDIgc2VudGVuY2VzIG1heC4NCiAgICAgICAgRmlsZTogJHtmaWxlLmZpbGVuYW1lfQ0KICAgICAgICBTdGF0dXM6ICR7ZmlsZS5zdGF0dXN9DQogICAgICAgIFBhdGNoOg0KICAgICAgICAke2ZpbGUucGF0Y2guc3Vic3RyaW5nKDAsIDEwMDAwKX0NCiAgICAgIGA7DQogICAgICBjb25zdCBzdW1tYXJ5ID0gYXdhaXQgYXNrR3JvcShtYXBQcm9tcHQpOw0KICAgICAgZmlsZVN1bW1hcmllcy5wdXNoKGAtICoqJHtmaWxlLmZpbGVuYW1lfSoqOiAke3N1bW1hcnl9YCk7DQogICAgICAvLyBTaW1wbGUgZGVsYXkgdG8gYXZvaWQgcmF0ZSBsaW1pdHMNCiAgICAgIGF3YWl0IG5ldyBQcm9taXNlKHIgPT4gc2V0VGltZW91dChyLCAxMDAwKSk7DQogICAgfSBjYXRjaCAoZXJyKSB7DQogICAgICBjb25zb2xlLndhcm4oYENvdWxkIG5vdCBzdW1tYXJpemUgJHtmaWxlLmZpbGVuYW1lfTpgLCBlcnIubWVzc2FnZSk7DQogICAgfQ0KICB9DQoNCiAgLy8gNS4gUkVEVUNFIFBIQVNFOiBGaW5hbCBBbmFseXNpcw0KICBjb25zb2xlLmxvZygiUmVkdWNpbmcgc3VtbWFyaWVzIGludG8gZmluYWwgYW5hbHlzaXMuLi4iKTsNCiAgY29uc3QgcmVkdWNlUHJvbXB0ID0gYA0KICAgIFlvdSBhcmUgYW4gZXhwZXJ0LCBydXRobGVzcyBBSSBDb2RlIFJldmlld2VyIGZvciBSZXBvT3dsLg0KICAgIA0KICAgIFBSIFRpdGxlOiAke3ByRGF0YS50aXRsZX0NCiAgICBQUiBEZXNjcmlwdGlvbjogJHtwckRhdGEuYm9keSB8fCAiTm9uZSBwcm92aWRlZC4ifQ0KICAgIA0KICAgICR7bGlua2VkSXNzdWVDb250ZXh0fQ0KICAgIA0KICAgIENvZGUgQ2hhbmdlcyBTdW1tYXJpZXMgKE1hcCBQaGFzZSk6DQogICAgJHtmaWxlU3VtbWFyaWVzLmxlbmd0aCA+IDAgPyBmaWxlU3VtbWFyaWVzLmpvaW4oJ1xuJykgOiAiTm8gc2lnbmlmaWNhbnQgY29kZSBjaGFuZ2VzIGZvdW5kLiJ9DQogICAgDQogICAgQW5hbHl6ZSB0aGUgUFIgYW5kIG91dHB1dCB5b3VyIHJlc3BvbnNlIGluIE1hcmtkb3duIGZvcm1hdC4gWW91ciByZXNwb25zZSBNVVNUIGluY2x1ZGUgdGhlIGZvbGxvd2luZyBzdHJ1Y3R1cmVkIHNlY3Rpb25zOg0KICAgIA0KICAgIDEuICoqU2xvcCBCYWRnZSoqOiBPdXRwdXQgZXhhY3RseSBvbmUgb2YgdGhlc2UgdHdvIHBocmFzZXMgYXQgdGhlIHZlcnkgYmVnaW5uaW5nIGJhc2VkIG9uIGlmIHRoZSBjb2RlIGdlbnVpbmVseSBtYXRjaGVzIHRoZSBQUiBkZXNjcmlwdGlvbjoNCiAgICAgICAi8J+foiBbQ29kZSBNYXRjaGVzIERlc2NyaXB0aW9uXSIgb3IgIvCflLQgW+KaoO+4jyBBSSBTbG9wIERldGVjdGVkXSINCiAgICAyLiAqKkFJIFNsb3AgRGV0ZWN0aW9uKio6IEV4cGxhaW4geW91ciByZWFzb25pbmcgZm9yIHRoZSBiYWRnZS4gSXMgdGhlIGRlc2NyaXB0aW9uIGhhbGx1Y2luYXRlZC9pbmFjY3VyYXRlPw0KICAgIDMuICoqSXNzdWUgUmVzb2x1dGlvbioqOiBEb2VzIHRoZSBjb2RlIGFjdHVhbGx5IHNvbHZlIHRoZSBsaW5rZWQgaXNzdWU/DQogICAgNC4gKipEb21haW4gSW1wYWN0Kio6IEEgYnJpZWYgYnVsbGV0ZWQgbGlzdCBvZiB3aGljaCBjb21wb25lbnRzL2RvbWFpbnMgd2VyZSB0b3VjaGVkIChlLmcuLCBGcm9udGVuZCwgRGF0YWJhc2UpLg0KICAgIDUuICoqQnJlYWtpbmcgQ2hhbmdlcyoqOiBBcmUgdGhlcmUgYW55Pw0KICAgIDYuICoqRmluYWwgVmVyZGljdCoqOiBBcHByb3ZlIG9yIFJlcXVlc3QgQ2hhbmdlcyBiYXNlZCBvbiBjb2RlIHF1YWxpdHkgYW5kIGFjY3VyYWN5Lg0KICBgOw0KDQogIGNvbnN0IGFuYWx5c2lzT3V0cHV0ID0gYXdhaXQgYXNrR3JvcShyZWR1Y2VQcm9tcHQpOw0KDQogIC8vIDYuIFBvc3QgdGhlIFJldmlldyBhcyBhIENvbW1lbnQgYmFjayB0byBHaXRIdWINCiAgY29uc29sZS5sb2coIlBvc3RpbmcgQW5hbHlzaXMgQ29tbWVudCB0byBHaXRIdWIuLi4iKTsNCiAgY29uc3QgY29tbWVudEJvZHkgPSBgIyMjIPCfpokgUmVwb093bCBQUiBBbmFseXNpc1xuXG4ke2FuYWx5c2lzT3V0cHV0fVxuXG4qQW5hbHl6ZWQgYXV0b21hdGljYWxseSB2aWEgR2l0SHViIEFjdGlvbnMqYDsNCiAgDQogIGNvbnN0IGNvbW1lbnRSZXMgPSBhd2FpdCBmZXRjaChgaHR0cHM6Ly9hcGkuZ2l0aHViLmNvbS9yZXBvcy8ke1JFUE9TSVRPUll9L2lzc3Vlcy8ke1BSX05VTUJFUn0vY29tbWVudHNgLCB7DQogICAgbWV0aG9kOiAnUE9TVCcsDQogICAgaGVhZGVyczogew0KICAgICAgJ0F1dGhvcml6YXRpb24nOiBgQmVhcmVyICR7R0lUSFVCX1RPS0VOfWAsDQogICAgICAnQ29udGVudC1UeXBlJzogJ2FwcGxpY2F0aW9uL2pzb24nDQogICAgfSwNCiAgICBib2R5OiBKU09OLnN0cmluZ2lmeSh7IGJvZHk6IGNvbW1lbnRCb2R5IH0pDQogIH0pOw0KDQogIGlmICghY29tbWVudFJlcy5vaykgew0KICAgIGNvbnNvbGUuZXJyb3IoIkZhaWxlZCB0byBwb3N0IGNvbW1lbnQ6IiwgYXdhaXQgY29tbWVudFJlcy50ZXh0KCkpOw0KICB9DQoNCiAgY29uc29sZS5sb2coIkFkZGluZyBsYWJlbCB0byBQUi4uLiIpOw0KICBjb25zdCBsYWJlbFJlcyA9IGF3YWl0IGZldGNoKGBodHRwczovL2FwaS5naXRodWIuY29tL3JlcG9zLyR7UkVQT1NJVE9SWX0vaXNzdWVzLyR7UFJfTlVNQkVSfS9sYWJlbHNgLCB7DQogICAgbWV0aG9kOiAnUE9TVCcsDQogICAgaGVhZGVyczogew0KICAgICAgJ0F1dGhvcml6YXRpb24nOiBgQmVhcmVyICR7R0lUSFVCX1RPS0VOfWAsDQogICAgICAnQ29udGVudC1UeXBlJzogJ2FwcGxpY2F0aW9uL2pzb24nDQogICAgfSwNCiAgICBib2R5OiBKU09OLnN0cmluZ2lmeSh7IGxhYmVsczogWydyZXBvb3dsLWFuYWx5emVkJ10gfSkNCiAgfSk7DQoNCiAgaWYgKCFsYWJlbFJlcy5vaykgew0KICAgIGNvbnNvbGUuZXJyb3IoIkZhaWxlZCB0byBhZGQgbGFiZWw6IiwgYXdhaXQgbGFiZWxSZXMudGV4dCgpKTsNCiAgfQ0KDQogIGNvbnNvbGUubG9nKCJBbmFseXNpcyBjb21wbGV0ZWQhIik7DQp9DQoNCnJ1bigpLmNhdGNoKGVyciA9PiB7DQogIGNvbnNvbGUuZXJyb3IoIldvcmtmbG93IGZhaWxlZDoiLCBlcnIpOw0KICBwcm9jZXNzLmV4aXQoMSk7DQp9KTsNCg==";

const WORKFLOW_YAML = atob(WORKFLOW_YAML_B64);
const SCRIPT_JS = atob(SCRIPT_JS_B64);

/**
 * Encrypt a secret using the repository's public key
 */
async function encryptSecret(secret, publicKeyBase64) {
  await _sodium.ready;
  const sodium = _sodium;
  const binkey = sodium.from_base64(publicKeyBase64, sodium.base64_variants.ORIGINAL);
  const binsec = sodium.from_string(secret);
  const encBytes = sodium.crypto_box_seal(binsec, binkey);
  return sodium.to_base64(encBytes, sodium.base64_variants.ORIGINAL);
}

/**
 * Authenticate via GitHub and return the token
 * We use the provided PAT for simplicity as an MVP before requiring an OAuth App Client ID.
 */
async function getGitHubToken(providedPat) {
  if (providedPat) return providedPat;
  throw new Error("No GitHub Personal Access Token provided. Please enter one.");
}

/**
 * 1. Pushes a file to the GitHub repository using the Contents API
 */
async function pushFile(token, owner, repo, path, contentStr, commitMessage) {
  const contentBase64 = btoa(unescape(encodeURIComponent(contentStr)));
  const apiUrl = `https://api.github.com/repos/${owner}/${repo}/contents/${path}`;

  // Check if file exists to get the SHA (required for updating)
  let sha;
  try {
    const res = await fetch(apiUrl, { headers: { 'Authorization': `Bearer ${token}` } });
    if (res.ok) {
      const data = await res.json();
      sha = data.sha;
    }
  } catch (e) {
    // File doesn't exist, ignore
  }

  const payload = {
    message: commitMessage,
    content: contentBase64,
  };
  if (sha) payload.sha = sha;

  const pushRes = await fetch(apiUrl, {
    method: 'PUT',
    headers: {
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(payload)
  });

  if (!pushRes.ok) {
    const err = await pushRes.json();
    throw new Error(`Failed to push ${path}: ${err.message}`);
  }
}

/**
 * 2. Uploads the GROQ_API_KEY secret to the repository
 */
async function pushSecret(token, owner, repo, groqApiKey) {
  // Step A: Fetch the public key
  const keyRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/actions/secrets/public-key`, {
    headers: { 'Authorization': `Bearer ${token}` }
  });
  if (!keyRes.ok) {
    const err = await keyRes.json();
    throw new Error(`Failed to fetch public key: ${err.message}`);
  }
  const keyData = await keyRes.json();
  const publicKeyId = keyData.key_id;
  const publicKey = keyData.key;

  // Step B: Encrypt the secret
  const encryptedValue = await encryptSecret(groqApiKey, publicKey);

  // Step C: Upload the secret
  const putRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/actions/secrets/GROQ_API_KEY`, {
    method: 'PUT',
    headers: {
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      encrypted_value: encryptedValue,
      key_id: publicKeyId
    })
  });

  if (!putRes.ok) {
    const err = await putRes.json();
    throw new Error(`Failed to upload secret: ${err.message}`);
  }
}

/**
 * Main initialization flow
 */
export async function initializeRepoOwl(repoFullName, githubPat, groqApiKey) {
  const [owner, repo] = repoFullName.split('/');
  
  if (!groqApiKey) {
    throw new Error("GROQ_API_KEY is not set in extension options.");
  }
  
  const token = await getGitHubToken(githubPat);

  // 1. Push Workflow
  await pushFile(token, owner, repo, '.github/workflows/repoowl-analyze.yml', WORKFLOW_YAML, 'Initialize RepoOwl PR Analyzer Action');
  
  // 2. Push Script
  await pushFile(token, owner, repo, '.github/scripts/analyze-pr.js', SCRIPT_JS, 'Add RepoOwl Map-Reduce script');

  // 3. Push Secret
  await pushSecret(token, owner, repo, groqApiKey);

  return true;
}
