-- 1. The Core Issues Table (Repository Specific)
CREATE TABLE IF NOT EXISTS issues (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  repo_name TEXT NOT NULL,
  issue_number INT NOT NULL,
  is_duplicate BOOLEAN DEFAULT FALSE,
  analysis_summary TEXT,
  status TEXT DEFAULT 'open',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE issues ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_issues_status ON issues(status);

-- Security Policy: The public (contributors) can READ the insights
CREATE POLICY "Allow public read access" ON issues 
FOR SELECT USING (true);

-- Security Policy: Only authenticated users can INSERT insights
CREATE POLICY "Allow maintainer write access" ON issues 
FOR INSERT WITH CHECK (auth.role() IN ('authenticated', 'anon'));

-- Security Policy: Authenticated users can also UPDATE (e.g. status)
CREATE POLICY "Allow maintainer update access" ON issues 
FOR UPDATE USING (auth.role() IN ('authenticated', 'anon')) WITH CHECK (auth.role() IN ('authenticated', 'anon'));

-- 2. The Global Ecosystem Registry (For the Showcase Tab)
CREATE TABLE IF NOT EXISTS public_ecosystem_registry (
  repo_name TEXT PRIMARY KEY,
  total_issues_analyzed INT DEFAULT 0,
  duplicates_found INT DEFAULT 0,
  maintainer_handle TEXT,
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE public_ecosystem_registry ENABLE ROW LEVEL SECURITY;

-- Security Policy: Anyone can view the ecosystem registry
CREATE POLICY "Allow public read on registry" ON public_ecosystem_registry 
FOR SELECT USING (true);

-- Security Policy: Authenticated users can INSERT new project stats
CREATE POLICY "Allow maintainer insert to registry" ON public_ecosystem_registry
FOR INSERT WITH CHECK (auth.role() IN ('authenticated', 'anon'));

-- Security Policy: Authenticated users can UPDATE their project's global stats
CREATE POLICY "Allow maintainer updates to registry" ON public_ecosystem_registry
FOR UPDATE USING (auth.role() IN ('authenticated', 'anon')) WITH CHECK (auth.role() IN ('authenticated', 'anon'));

-- 3. Central Registry (For Contributor Discovery)
CREATE TABLE IF NOT EXISTS registry (
  owner TEXT NOT NULL,
  repo TEXT NOT NULL,
  supabase_url TEXT NOT NULL,
  supabase_anon_key TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  PRIMARY KEY (owner, repo)
);

ALTER TABLE registry ENABLE ROW LEVEL SECURITY;

-- Security Policy: The public (contributors) can READ the registry to discover keys
CREATE POLICY "Allow public read access to registry" ON registry
FOR SELECT USING (true);

-- Insert/Update is handled by the Edge Function (using service role), so no policies needed for authenticated users.
