-- RepoOwl v1.0 BYOK Database Schema
-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS issues (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  repo_name TEXT NOT NULL,
  issue_number INT NOT NULL,
  is_duplicate BOOLEAN DEFAULT FALSE,
  analysis_summary TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) so the database is secure
ALTER TABLE issues ENABLE ROW LEVEL SECURITY;

-- Allow the user's extension to read and write to their own database
CREATE POLICY "Allow public access for extension" ON issues FOR ALL USING (true);
