const fs = require('fs');
const workflow = fs.readFileSync('.github/workflows/repoowl-analyze.yml', 'utf8');
const script = fs.readFileSync('.github/scripts/analyze-pr.js', 'utf8');
const workflowB64 = Buffer.from(workflow).toString('base64');
const scriptB64 = Buffer.from(script).toString('base64');
let installer = fs.readFileSync('extension/src/background/githubInstaller.js', 'utf8');
installer = installer.replace(/const WORKFLOW_YAML_B64 = ".*";/, 'const WORKFLOW_YAML_B64 = "' + workflowB64 + '";');
installer = installer.replace(/const SCRIPT_JS_B64 = ".*";/, 'const SCRIPT_JS_B64 = "' + scriptB64 + '";');
fs.writeFileSync('extension/src/background/githubInstaller.js', installer);
console.log('Successfully updated Base64 strings in githubInstaller.js');
