/**
 * Shared schema SQL string for Supabase Edge Functions.
 * This is the Deno/TypeScript equivalent of extension/src/lib/schema.js.
 * Keep both files in sync when making schema changes.
 */
export const DATABASE_SCHEMA_SQL = `
-- 1. The Core Issues Table (Repository Specific)
CREATE TABLE IF NOT EXISTS issues (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  repo_name TEXT NOT NULL,
  issue_number INT NOT NULL,
  is_duplicate BOOLEAN DEFAULT FALSE,
  analysis_summary TEXT,
  affected_files JSONB,           -- Array of file paths predicted to be affected by this issue
  status TEXT DEFAULT 'open',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(repo_name, issue_number)
);

ALTER TABLE issues ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_issues_status ON issues(status);

DROP POLICY IF EXISTS "Allow public read access" ON issues;
CREATE POLICY "Allow public read access" ON issues 
FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow maintainer write access" ON issues;
CREATE POLICY "Allow maintainer write access" ON issues 
FOR INSERT WITH CHECK (auth.role() IN ('authenticated', 'anon'));

DROP POLICY IF EXISTS "Allow maintainer update access" ON issues;
CREATE POLICY "Allow maintainer update access" ON issues 
FOR UPDATE USING (auth.role() IN ('authenticated', 'anon')) WITH CHECK (auth.role() IN ('authenticated', 'anon'));

-- 2. The Global Ecosystem Registry
CREATE TABLE IF NOT EXISTS public_ecosystem_registry (
  repo_name TEXT PRIMARY KEY,
  total_issues_analyzed INT DEFAULT 0,
  duplicates_found INT DEFAULT 0,
  maintainer_handle TEXT,
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE public_ecosystem_registry ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read on registry" ON public_ecosystem_registry;
CREATE POLICY "Allow public read on registry" ON public_ecosystem_registry 
FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow maintainer insert to registry" ON public_ecosystem_registry;
CREATE POLICY "Allow maintainer insert to registry" ON public_ecosystem_registry
FOR INSERT WITH CHECK (auth.role() IN ('authenticated', 'anon'));

DROP POLICY IF EXISTS "Allow maintainer updates to registry" ON public_ecosystem_registry;
CREATE POLICY "Allow maintainer updates to registry" ON public_ecosystem_registry
FOR UPDATE USING (auth.role() IN ('authenticated', 'anon')) WITH CHECK (auth.role() IN ('authenticated', 'anon'));

-- 3. Central Registry (For Contributor Discovery)
CREATE TABLE IF NOT EXISTS registry (
  owner TEXT NOT NULL,
  repo TEXT NOT NULL,
  supabase_url TEXT NOT NULL,
  supabase_anon_key TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  PRIMARY KEY (owner, repo)
);

ALTER TABLE registry ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access to registry" ON registry;
CREATE POLICY "Allow public read access to registry" ON registry
FOR SELECT USING (true);

-- 4. Pull Requests
CREATE TABLE IF NOT EXISTS pull_requests (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  repo_name TEXT NOT NULL,
  pr_number INT NOT NULL,
  slop_detection JSONB,
  issue_resolution JSONB,
  domain_impact JSONB,
  recommended_labels JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(repo_name, pr_number)
);

ALTER TABLE pull_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access to pull_requests" ON pull_requests;
CREATE POLICY "Allow public read access to pull_requests" ON pull_requests 
FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow maintainer write access to pull_requests" ON pull_requests;
CREATE POLICY "Allow maintainer write access to pull_requests" ON pull_requests 
FOR INSERT WITH CHECK (auth.role() IN ('authenticated', 'anon'));

DROP POLICY IF EXISTS "Allow maintainer update access to pull_requests" ON pull_requests;
CREATE POLICY "Allow maintainer update access to pull_requests" ON pull_requests 
FOR UPDATE USING (auth.role() IN ('authenticated', 'anon')) WITH CHECK (auth.role() IN ('authenticated', 'anon'));
`;
