name: Security Report
description: Report a security vulnerability
title: "[SECURITY]: "
labels:
  - security

body:
  - type: input
    id: type
    attributes:
      label: Vulnerability Type
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low
        - Medium
        - High
        - Critical

  - type: input
    id: components
    attributes:
      label: Affected Components

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce

  - type: textarea
    id: impact
    attributes:
      label: Impact

  - type: textarea
    id: fix
    attributes:
      label: Suggested Fix
