name: Test Coverage
description: Suggest tests for existing code
title: "[TEST]: "
labels:
  - tests

body:
  - type: input
    id: module
    attributes:
      label: Module
    validations:
      required: true

  - type: input
    id: coverage
    attributes:
      label: Current Coverage

  - type: textarea
    id: missing
    attributes:
      label: Missing Tests

  - type: textarea
    id: suggested
    attributes:
      label: Suggested Test Cases
